environment: REFORM_ENVIRONMENT
NODE_ENV: NODE_ENV

node:
  port: PORT
  baseUrl: BASE_URL

session:
  secret: SESSION_SECRET

tests:
  e2e:
    waitForTimeout: E2E_WAIT_FOR_TIMEOUT_VALUE
    waitForAction: E2E_WAIT_FOR_ACTION_VALUE
    outputDir: E2E_OUTPUT_DIR
    url: TEST_URL
    proxy: E2E_IDAM_PROXY
    proxyByPass: E2E_IDAM_SERVER
    addWaitForCrossBrowser: E2E_ADD_WAIT_CROSSBROWSER
    idam:
      idamTestUsername: E2E_IDAM_USERNAME
      idamTestPassword: E2E_IDAM_PASSWORD
      idamTestForename: IDAM_TEST_FORENAME
      idamTestSurname: IDAM_TEST_SURNAME
      idamTestUserGroup: IDAM_TEST_USER_GROUP
      idamTestLevelOfAccess: IDAM_TEST_LEVEL_OF_ACCESS
      idamTestSupportCreateAccountEndpoint: IDAM_TEST_SUPPORT_CREATE_ACCOUNT_ENDPOINT

ssl:
  hpkp:
    maxAge: HPKP_MAX_AGE
    sha256s: HPKP_SHAS

services:
  redis:
    url: REDISCLOUD_URL
    useSSL: USE_SSL
    encryptionAtRestKey: REDIS_ENCRYPTION_SECRET
  idam:
    apiHealth: IDAM_APP_HEALHCHECK_URL
    authenticationHealth: IDAM_AUTHENTICATION_HEALHCHECK_URL
    apiUrl: IDAM_API_URL
    secret: IDAM_SECRET
    loginUrl: IDAM_LOGIN_URL
    clientId: IDAM_CLIENT_ID
  googleAnalytics:
    id: GOOGLE_ANALYTICS_ID
    trackingUrl: GOOGLE_ANALYTICS_TRACKING_URL
  applicationInsights:
    instrumentationKey: APPINSIGHTS_INSTRUMENTATIONKEY
  rateLimiter:
    total: RATE_LIMITER_TOTAL
    expire: RATE_LIMITER_EXPIRE
    enabled: RATE_LIMITER_ENABLED
  caseOrchestration:
    baseUrl: COS_BASE_URL
    health: COS_HEALTHCHECK_URL
  dnFrontend:
    url: DECREE_NISI_FRONTEND_URL
  daFrontend:
    url: DECREE_ABSOLUTE_FRONTEND_URL
  caseMaintenance:
    baseUrl: CASE_MAINTENANCE_BASE_URL
  feesAndPayments:
    baseUrl: FEES_AND_PAYMENTS_URL
    health: FEES_AND_PAYMENTS_HEALTHCHECK_URL
  proxyUrl: PROXY_URL
  evidenceManagement:
    baseUrl: EVIDENCE_MANAGEMENT_CLIENT_API_URL
    health: EVIDENCE_MANAGEMENT_CLIENT_API_HEALTHCHECK_URL
    downloadEndPoint: EVIDENCE_MANAGEMENT_CLIENT_API_DOWNLOAD_ENDPOINT
  webchat:
    chatId: WEBCHAT_CHAT_ID
    tenant: WEBCHAT_TENANT
    buttonNoAgents: WEBCHAT_BUTTON_NO_AGENTS
    buttonAgentsBusy: WEBCHAT_BUTTON_AGENTS_BUSY
    buttonServiceClosed: WEBCHAT_BUTTON_SERVICE_CLOSED
  postcode:
    baseUrl: POST_CODE_URL
    token: POST_CODE_ACCESS_TOKEN

features:
  idam: FEATURE_IDAM
  respSolicitorDetails: FEATURE_RESP_SOLICITOR_DETAILS
  webchat: FEATURE_WEBCHAT

journey:
  timeoutDelay: JOURNEY_TIMEOUT_DELAY

featureToggles:
  launchDarklyKey: LAUNCHDARKLY_KEY
