environment: development
NODE_ENV: development

node:
  port: 3000
  baseUrl: https://localhost:3000

session:
  secret: sessionSecret
  secure: true
  expires: 3600000 # 60 minutes

ssl:
  hpkp:
    maxAge: 3600
    sha256s: AbCdEf123=
    sha256sBackup: ZyXwVu456=

health:
  timeout: 10000
  deadline: 15000

service:
  name: 'divorce-respondent-frontend'

services:
  redis:
    url: redis://127.0.0.1:6379
    useSSL: false
    encryptionAtRestKey: encryptionAtRestKey
  idam:
    apiHealth: https://localhost:8001/health
    authenticationHealth: https://localhost:3000/health
    apiUrl: http://localhost:3001/idam
    secret: '123456'
    loginUrl: https://localhost:3000/idam-mock-login
    clientId: 'divorce'
  sourceLabs:
    browser: 'chrome'
    username: 'username'
    key: 'privatekey'
    tunnelId: ''
    waitForTimeout: 30000
  googleAnalytics:
    id: TBD
    trackingUrl: https://localhost:3000/
  applicationInsights:
    instrumentationKey: 'dummy-key'
  rateLimiter:
    total: 3600 # 1 req/s on average per hour
    expire: 3600000
    enabled: false
  caseOrchestration:
    getPetitionUrl: http://localhost:3001/case-orchestration/retrieve-aos-case
    linkRespondentUrl: http://localhost:3001/case-orchestration/link-respondent
    submitAosUrl: http://localhost:3001/case-orchestration/submit-aos
    health: http://localhost:3001/health
  dnFrontend:
    url: https://localhost:4000
    landing: /authenticated
  caseMaintenance:
    baseUrl: http://localhost:3001/case-maintenance
  feesAndPayments:
    baseUrl: http://localhost:3001
    health: http://localhost:3001/health
  proxyUrl: ''

paths:
  health: /health
  index: /
  entry: /entry
  end: /end
  termsAndConditions: /terms-and-conditions
  cookiesPolicy: /cookie
  privacyPolicy: /privacy-policy
  authenticated: /authenticated
  captureCaseAndPin: /respond-with-pin
  mock:
    idamLogin: /idam-mock-login
  respondent:
    financialSituation: /delay-the-decree
    respond: /respond
    reviewApplication: /review-application
    consentDecree: /consent-to-the-decree
    admitAdultery: /admit-the-adultery
    chooseAResponse: /choose-a-response
    confirmDefence: /defend-are-you-sure
    defendFinancialHardship: /defend-financial-hardship
    jurisdiction: /jurisdiction
    legalProceedings: /legal-proceedings
    agreeToPayCosts: /agree-to-pay-costs
    contactDetails: /contact-details
    checkYourAnswers: /check-your-answers
    invalidCaseState: /invalid-case-state
    noConsentAreYouSure: /no-consent-are-you-sure
    progressBar: /progress-bar
    done: /done
  correspondent:
    respond: /corespondent-aos/progress-bar/respond
    reviewApplication: /corespondent-aos/review-application

tests:
  e2e:
    show: true
    waitForTimeout: 10000
    waitForAction: 1000
    smartWait: 5000
    outputDir: ../../functional-output
    proxy: ''
    proxyByPass: ''
    idam:
      idamTestUsername:
      idamTestPassword:
      idamTestForename:
      idamTestSurname:
      idamTestUserGroup:
      idamTestLevelOfAccess:
      idamTestSupportCreateAccountEndpoint:

features:
  idam: false
  agreeToCosts:
    differentAmount:
      enabled: false

journey:
  timeoutDelay: 300
