tests:
  e2e:
    show: false
    proxy: ''
    proxyByPass: ''
    outputDir: './functional-output'
    addWaitForCrossBrowser: true

services:
  idam:
    apiUrl: https://idam-api.aat.platform.hmcts.net
  caseMaintenance:
    baseUrl: http://div-cms-aat.service.core-compute-aat.internal

features:
  idam: false
  respSolicitorDetails: false
