# For running tests locally against AAT
environment: local-aat

services:
  idam:
    apiUrl: https://idam-api.aat.platform.hmcts.net
    secret: <get-from-vault> # DO NOT SET HERE - MAKE A COPY OF THIS FILE AS `local-aat.yml`
  caseMaintenance:
    baseUrl: http://div-cms-aat.service.core-compute-aat.internal

tests:
  e2e:
    show: true
    url: https://respond-divorce-aks.aat.platform.hmcts.net


features:
  idam: true
  respondentEquality: 'true'
  coRespondentEquality: 'true'
